Repository HobnobMancer/cazy_webscraper, pull requests merged in 2020-12, with the labels that each got.

#14 fixes issue #13 (unnecessary files)
  cazy_webscraper.egg-info/PKG-INFO
  cazy_webscraper.egg-info/SOURCES.txt
  cazy_webscraper.egg-info/dependency_links.txt
  cazy_webscraper.egg-info/entry_points.txt
  cazy_webscraper.egg-info/requires.txt
  cazy_webscraper.egg-info/top_level.txt
  scraper/__pycache__/__init__.cpython-38.pyc
  scraper/__pycache__/cazy_webscraper.cpython-38.pyc
  scraper/file_io/__pycache__/__init__.cpython-38.pyc
  scraper/parse/__pycache__/__init__.cpython-38.pyc
  scraper/utilities/__pycache__/__init__.cpython-38.pyc
Labels: enhancement

#11 fixes issue #8 (no .gitignore)
  .gitignore
Labels: enhancement

#15 Bug fixing
  scraper/cazy_webscraper.py
  tests/test_inputs/test_inputs_webscraper/protein_no_genbank.html
  tests/test_inputs/test_inputs_webscraper/protein_with_genbank_synonyms.html
  tests/test_webscraper.py
Labels: bug, enhancement

#20 fix issue #19 - inconsistent dependency definitions
  environment.yml
  requirements.txt
  setup.py
Labels: bug
